#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
DB_PATH=${PROGRESS_DB:-"$PROJECT_ROOT/state/progress.db"}
JAR_PATH=${GROUND_TRUTH_JAR:-"$PROJECT_ROOT/ground_truth/26.1.2.jar"}
MANIFEST_PATH=${GROUND_TRUTH_MANIFEST:-"$PROJECT_ROOT/ground_truth/26.1.2.json"}
GRADLE_PROPERTIES_PATH="$PROJECT_ROOT/gradle.properties"
TOOL_VERSIONS_PATH="$PROJECT_ROOT/.tool-versions"
ADR_PATH="$PROJECT_ROOT/docs/adr/0001-toolchain-pin.md"
GRADLE_VERSION=${GRADLE_VERSION:-"9.5.0"}
MODE="apply"

usage() {
  cat >&2 <<'USAGE'
usage: scripts/probe-toolchain.sh [--dry-run] [--apply]

Pins the toolchain from the Mojang manifest plus classfile fingerprint.
This is the first cascade stage; brute-force javac probing belongs to a later
Autoresearch mission once Gradle compilation exists.
USAGE
}

sql_quote() {
  printf "%s" "$1" | sed "s/'/''/g"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

write_file() {
  local path=$1
  local content=$2

  if [ "$MODE" = "dry-run" ]; then
    printf '%s\n--- %s ---\n%s\n' "[dry-run] would write:" "$path" "$content"
  else
    mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" > "$path"
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      MODE="dry-run"
      shift
      ;;
    --apply)
      MODE="apply"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

require_command jq
require_command python3
require_command sqlite3

if [ ! -f "$MANIFEST_PATH" ]; then
  echo "missing manifest: $MANIFEST_PATH" >&2
  exit 1
fi

if [ ! -f "$JAR_PATH" ]; then
  echo "missing ground-truth jar: $JAR_PATH" >&2
  exit 1
fi

if [ ! -f "$DB_PATH" ]; then
  echo "missing progress database: $DB_PATH" >&2
  echo "run scripts/init-progress-db.sh first" >&2
  exit 1
fi

manifest_component=$(jq -r '.javaVersion.component // empty' "$MANIFEST_PATH")
manifest_major=$(jq -r '.javaVersion.majorVersion // empty' "$MANIFEST_PATH")

if [ -z "$manifest_component" ] || [ -z "$manifest_major" ]; then
  echo "manifest does not contain javaVersion.component and javaVersion.majorVersion" >&2
  exit 1
fi

fingerprint=$(
  python3 - "$JAR_PATH" <<'PY'
import collections
import struct
import sys
import zipfile

jar_path = sys.argv[1]
counts = collections.Counter()

with zipfile.ZipFile(jar_path) as jar:
  for name in jar.namelist():
    if not name.endswith(".class"):
      continue

    with jar.open(name) as class_file:
      header = class_file.read(8)

    magic, minor, major = struct.unpack(">IHH", header)
    if magic != 0xCAFEBABE:
      raise SystemExit(f"invalid class header: {name}")
    counts[(major, minor)] += 1

if not counts:
  raise SystemExit("no class files found")

((major, minor), count) = counts.most_common(1)[0]
language_version = major - 44
print(f"{major}\t{minor}\t{language_version}\t{count}")
PY
)

class_major=$(printf '%s' "$fingerprint" | cut -f1)
class_minor=$(printf '%s' "$fingerprint" | cut -f2)
class_language=$(printf '%s' "$fingerprint" | cut -f3)
fingerprint_count=$(printf '%s' "$fingerprint" | cut -f4)
local_java_version=$(java -version 2>&1 | sed -n '1s/.*version "\([^"]*\)".*/\1/p' || true)
toolchain_value="$manifest_component:$manifest_major"
quoted_component=$(sql_quote "$manifest_component")
quoted_toolchain=$(sql_quote "$toolchain_value")

gradle_properties=$(cat <<EOF
# Generated by scripts/probe-toolchain.sh from ground_truth/26.1.2.json.
toolchain.jdk=$toolchain_value
javaCompiler.languageVersion=$manifest_major
org.gradle.java.installations.fromEnv=JDK${manifest_major}_HOME,JAVA${manifest_major}_HOME,JAVA_HOME
gradle.version=$GRADLE_VERSION
EOF
)

tool_versions=$(cat <<EOF
# Mojang manifest component: $manifest_component
java openjdk-$manifest_major
EOF
)

adr=$(cat <<EOF
# ADR 0001 - Toolchain Pin

## Status

Accepted for bootstrap; revisit with Autoresearch brute-force probing after Gradle compilation exists.

## Context

The 26.1.2 manifest declares Java runtime component \`$manifest_component\` with major version \`$manifest_major\`. A classfile fingerprint of \`ground_truth/26.1.2.jar\` found major version \`$class_major\`, minor version \`$class_minor\`, which corresponds to Java \`$class_language\` across \`$fingerprint_count\` sampled-majority classes.

The currently active local Java reports \`${local_java_version:-unknown}\`. That runtime is not treated as the target compiler unless it also satisfies Java $manifest_major.

## Decision

Pin the bootstrap target to \`$toolchain_value\` and mirror it into:

- \`state/progress.db.toolchain\`
- \`gradle.properties\`
- \`.tool-versions\`
- \`gradle.properties\` also pins Gradle \`$GRADLE_VERSION\` for \`scripts/gradle.sh\`

## Consequences

Strict tier-A bytecode equality remains conditional on a later brute-force javac probe. Until Gradle build output exists, this project records the manifest and classfile fingerprint as the best available non-destructive evidence.
EOF
)

if [ "$class_language" != "$manifest_major" ]; then
  echo "warning: manifest Java $manifest_major differs from classfile Java $class_language" >&2
fi

if [ "$MODE" = "apply" ]; then
  sqlite3 "$DB_PATH" <<SQL
PRAGMA foreign_keys = ON;
BEGIN;
INSERT INTO toolchain_probes(vendor, major, minor, patch, source_id, chosen, probed_at)
SELECT '$quoted_component', $manifest_major, 0, 0, probe_sources.id, 1, CURRENT_TIMESTAMP
FROM probe_sources
WHERE probe_sources.name = 'MANIFEST'
  AND NOT EXISTS (
    SELECT 1
    FROM toolchain_probes
    JOIN probe_sources AS existing_sources ON existing_sources.id = toolchain_probes.source_id
    WHERE toolchain_probes.vendor = '$quoted_component'
      AND toolchain_probes.major = $manifest_major
      AND existing_sources.name = 'MANIFEST'
  );

INSERT INTO toolchain_probes(vendor, major, minor, patch, source_id, chosen, probed_at)
SELECT 'classfile', $class_language, $class_minor, $class_major, probe_sources.id, 0, CURRENT_TIMESTAMP
FROM probe_sources
WHERE probe_sources.name = 'FINGERPRINT'
  AND NOT EXISTS (
    SELECT 1
    FROM toolchain_probes
    JOIN probe_sources AS existing_sources ON existing_sources.id = toolchain_probes.source_id
    WHERE toolchain_probes.vendor = 'classfile'
      AND toolchain_probes.major = $class_language
      AND toolchain_probes.patch = $class_major
      AND existing_sources.name = 'FINGERPRINT'
  );

INSERT OR REPLACE INTO toolchain(component, value, probe_id, set_at)
SELECT 'jdk', '$quoted_toolchain', toolchain_probes.id, CURRENT_TIMESTAMP
FROM toolchain_probes
JOIN probe_sources ON probe_sources.id = toolchain_probes.source_id
WHERE toolchain_probes.vendor = '$quoted_component'
  AND toolchain_probes.major = $manifest_major
  AND probe_sources.name = 'MANIFEST'
ORDER BY toolchain_probes.id DESC
LIMIT 1;
COMMIT;
SQL
  sqlite3 "$DB_PATH" <<SQL
PRAGMA foreign_keys = ON;
INSERT OR REPLACE INTO toolchain(component, value, probe_id, set_at)
VALUES ('gradle', '$GRADLE_VERSION', NULL, CURRENT_TIMESTAMP);
SQL
fi

write_file "$GRADLE_PROPERTIES_PATH" "$gradle_properties"
write_file "$TOOL_VERSIONS_PATH" "$tool_versions"
write_file "$ADR_PATH" "$adr"

cat <<EOF
toolchain=$toolchain_value
classfile_major=$class_major
classfile_java=$class_language
local_java=${local_java_version:-unknown}
gradle=$GRADLE_VERSION
mode=$MODE
EOF
